name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: terms
    attributes:
      label: Please confirm the following
      description: I agree to follow the [Code of Conduct](https://example.com)
      options:
        - label: "I agree to follow this project's Code of Conduct"
          required: true
    id: searchedDuplicates
    attributes:
      label: Searched for Duplicates?
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I performed a cursory search of the [issue tracker](https://github.com/darkred/Userscripts/issues) to avoid opening a duplicate issue
          required: true
    id: testedClean
    attributes:
      label: Tested the script itself alone?
      description: "Make sure the bug is caused by the script: try disabling the other scripts (and extensions) first, and even better in a fresh browser profile."
      options:
        - label: I tested the script disabling all others, and if needed in a fresh profile.
        required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen? Provide STR (steps to reproduce).
      placeholder: |
      "Tell us what you see! When the script doesn't work, is it because it doesn't run at all in the page (check TM/VM's toolbar dropdown button), or because it has errors in Console?"  
      "If it's the former them its `@include` rule needs additions. If it's the latter, include the Console errors in the textarea below."
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: example-url
    attributes:
      label: Example URL
      description: Provide a full URL where the bug appears.
      placeholder: example.com/content
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What script manager are you using? (Greasemonkey is NOT supported)
      multiple: true
      options:
        - Tampermonkey
        - Violentmonkey
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: "Please drag'n'drop any screenshots/gif in so I can help you better."
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: "I agree to follow this project's Code of Conduct"
          required: true
